#!/bin/bash
#create config files
cd ~
mkdir -p ~/.config/easydl/
cd ~/.config/easydl/
if [ ! -f config.sh ]
then
    touch config.sh
    echo '#!/bin/bash' > config.sh
    echo "name1='nothing'" >> config.sh
    echo "directory1='nothing'" >> config.sh
    echo "name2='nothing'" >> config.sh
    echo "directory2='nothing'" >> config.sh
    echo "name3='nothing'" >> config.sh
    echo "directory3='nothing'" >> config.sh
    echo "name4='nothing'" >> config.sh
    echo "directory4='nothing'" >> config.sh
    echo "name5='nothing'" >> config.sh
    echo "directory5='nothing'" >> config.sh
fi


#set beggining variables
#set yes or no to yes so that it will default to thinking you want to download something
YORN='y'
#make this your first url on start
LINKS=0
#check the condition passed (if -a it will ask for aliases
if [ "$1" = '-a' ]
then
    cd ~/.config/easydl/
    lines=$(wc -l config.sh)
    lines=${lines/config.sh/}
    if [ $lines -gt 1 ]
    then
        numberofaliases=$(( 1 + ( $lines - 10 ) / 2 ))
    else
        numberofaliases=0
    fi
    read -p 'what do you want this alias to be named? (no spaces)> ' name
    read -p 'where do you want it to point? use the same syntax as if you were passing cd then this text from the home directory-> ' adirectory
    echo 'name'"$numberofaliases"'='"'""$name""'" >> config.sh
    echo 'directory'"$numberofaliases"'='"'""$adirectory""'" >> config.sh
elif [ "$1" = '-al' ]
then
    echo "your aliases are listed after all of the things being listed as nothing"
    echo "ctrl x to exit nano (the text editor)"
    sleep 5
    nano ~/.config/easydl/config.sh
else
    while [ "${YORN}" = 'y' ]
    do
        echo 'video (mp4) or audio (mp3)'
        read -p 'video or audio> ' format
        echo 'what url?'
        read -p 'paste url here (ctrl shift v)> ' url
        if [ $LINKS -gt 0 ]
        then
            echo 'same directory as before?'
            read -p 'y or n> ' yesorno
            if [ "${yesorno}" = 'n' ]
            then
                echo 'where do you want it?'
                read -p 'directory> ' place
                source ~/.config/easydl/config.sh
                if [ "${place}" = "$name1" ]
                then
                    realplace="$directory1"
                    cd ~
                    cd $directory1
                elif [ "${place}" = "$name2" ]
                then
                    realplace="$directory2"
                    cd ~
                    cd $directory2
                elif [ "${place}" = "$name3" ]
                then
                    realplace="$directory3"
                    cd ~
                    cd $directory3
                elif [ "${place}" = "$name4}" ]
                then
                    realplace="$directory4"
                    cd ~
                    cd $directory4
                elif [ "${place}" = "${name5}" ]
                then
                    realplace="$directory5"
                    cd ~
                    cd $directory5
                else
                    realplace="$place"
                    cd ~
                    cd $place
                fi
            fi
        elif [ $LINKS -eq 0 ]
        then
            echo 'where do you want it?'
            read -p 'directory> ' place
            source ~/.config/easydl/config.sh
            if [ "${place}" = "$name1" ]
            then
                realplace="$directory1"
                cd ~
                cd $directory1
            elif [ "${place}" = "$name2" ]
            then
                realplace="$directory2"
                cd ~
                cd $directory2
            elif [ "${place}" = "$name3" ]
            then
                realplace="$directory3"
                cd ~
                cd $directory3
            elif [ "${place}" = "$name4}" ]
            then
                realplace="$directory4"
                cd ~
                cd $directory4
            elif [ "${place}" = "${name5}" ]
            then
                realplace="$directory5"
                cd ~
                cd $directory5
            else
                realplace="$place"
                cd ~
                cd $place
            fi
        fi
        echo ''
        echo 'Downloading '$url' as a(n) '$format' file in ~/'$realplace
        echo ''
        sleep 2
        #this is where
        #you can
        #change the Youtube Commands!
        #
        #
        #
        if [ "${format}" = 'audio' ]
        then
            #right here for audio
            youtube-dl -x --audio-format "mp3" -o '%(title)s.%(ext)s' $url
        elif [ "${format}" = 'video' ]
        then
            #and right here for video
            youtube-dl -f mp4 -o '%(title)s.%(ext)s' $url
        else
            echo 'that is not understood, please type video or audio only'
        fi
        echo 'done, do you have more?'
        read -p 'y or n> ' YORN
        if [ "${YORN}" = 'y' ]
        then
            ((LINKS=LINKS+1))
        fi
    done

    echo 'have a nice day :)'
fi
exit
